{
  "success": true,
  "day": "today",
  "source": "https://www.kooora-lives1.info/matches-today/",
  "matches": [
    {
      "id": 1,
      "home_team": "زد",
      "away_team": "غزل المحلة",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/1683.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/7.png",
      "time": "05:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "أون سبورت",
      "commentator": "غير معروف",
      "league": "غير معروف",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 2,
      "home_team": "حرس الحدود",
      "away_team": "المقاولون العرب",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/149.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/08/8310.png",
      "time": "05:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "أون سبورت ماكس",
      "commentator": "غير معروف",
      "league": "غير معروف",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 3,
      "home_team": "الاتحاد السكندري",
      "away_team": "طلائع الجيش",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/13.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/304.png",
      "time": "08:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "أون سبورت",
      "commentator": "غير معروف",
      "league": "غير معروف",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 4,
      "home_team": "البنك الاهلي",
      "away_team": "بتروجت",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/06/50527.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/653.png",
      "time": "08:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "أون سبورت ماكس",
      "commentator": "غير معروف",
      "league": "غير معروف",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 5,
      "home_team": "فياريال",
      "away_team": "إشبيلية",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/127.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/126.png",
      "time": "08:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "beIN SPORTS HD 9",
      "commentator": "غير معروف",
      "league": "إسبانيا, الدوري الإسباني",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 6,
      "home_team": "إسبانيول",
      "away_team": "أتلتيك بلباو",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/119.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/07/144.png",
      "time": "08:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "beIN Sports 3 HD",
      "commentator": "غير معروف",
      "league": "إسبانيا, الدوري الإسباني",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 7,
      "home_team": "بريست",
      "away_team": "ستراسبورج",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/08/534.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/07/479.png",
      "time": "08:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "beIN SPORTS HD 4",
      "commentator": "غير معروف",
      "league": "فرنسا, الدوري الفرنسي",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 8,
      "home_team": "لاتسيو",
      "away_team": "إنتر ميلان",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/136.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/224.png",
      "time": "10:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "شاهد - Shahid VIP",
      "commentator": "غير معروف",
      "league": "إيطاليا, كأس إيطاليا - النهائي",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 9,
      "home_team": "لانس",
      "away_team": "باريس سان جيرمان",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/07/481.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/237.png",
      "time": "10:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "Bein Sports HD2",
      "commentator": "غير معروف",
      "league": "فرنسا, الدوري الفرنسي",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 10,
      "home_team": "خيتافي",
      "away_team": "ريال مايوركا",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/317.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/121.png",
      "time": "10:30 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "beIN SPORTS HD 4",
      "commentator": "غير معروف",
      "league": "إسبانيا, الدوري الإسباني",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 11,
      "home_team": "ألافيس",
      "away_team": "برشلونة",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/07/168.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/111.png",
      "time": "10:30 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "not-started",
      "status_text": "لم تبدأ بعد",
      "channel": "beIN Sports 3 HD",
      "commentator": "غير معروف",
      "league": "إسبانيا, الدوري الإسباني",
      "match_url": "https://www.kooora-lives1.info/"
    },
    {
      "id": 12,
      "home_team": "مانشستر سيتي",
      "away_team": "كريستال بالاس",
      "home_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/94.png",
      "away_logo": "https://www.kooora-lives1.info/wp-content/uploads/2025/05/299.png",
      "time": "10:00 PM",
      "score_home": "0",
      "score_away": "0",
      "status": "finished",
      "status_text": "انتهت",
      "channel": "beIN SPORTS HD 1",
      "commentator": "غير معروف",
      "league": "إنجلترا, الدوري الإنجليزي",
      "match_url": "https://www.kooora-lives1.info/matches/%d9%85%d8%a7%d9%86%d8%b4%d8%b3%d8%aa%d8%b1-%d8%b3%d9%8a%d8%aa%d9%8a-%d9%88-%d9%83%d8%b1%d9%8a%d8%b3%d8%aa%d8%a7%d9%84-%d8%a8%d8%a7%d9%84%d8%a7%d8%b3-%d9%81%d9%8a-%d8%a5%d9%86%d8%ac%d9%84%d8%aa%d8%b1/"
    }
  ]
}
